### ISSUE TITLE
#include <algorithm> ?

### ISSUE THREAD

**Issue by ctralie** [Ripser/ripser#1]
Hi Uli,
To get this to work, I had to add #include <algorithm> at the top.  Am I missing something?
Thanks,
Chris
P.S. Amazing code!!

**Comment by ubauer** [comment]
Hi Chris,

I assume that it is somehow included by some other file in my tool chain but not in yours. Which compiler are you using?

Best, Uli

**Comment by ctralie** [comment]
g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413

**Comment by ubauer** [comment]
Thanks. It's fixed now both in dev and master.
