### ISSUE TITLE
Example for loading upper triangular matrix to ripser

### ISSUE THREAD

**Issue by akatav** [Ripser/ripser#12]
Please provide an example file on how to provide an upper triangular matrix that has unit diagonal. I have a (symmetric) correlation matirx with unit diagonal. I have extracted the upper triangular portion of this and written to a csv file. It has 264 columns at the max and 264 rows.

**Comment by sauln** [comment]
What did you try?

I would expect
```
./ripser --format upper-distance --input INPUT --output OUTPUT
```
would work.

Does it not? I don't think you should include the diagonal though.

**Comment by ubauer** [comment]
Hi,

Ripser assumes distance matrices, not correlation matrices. But the triangle inequality is not required. An easy fix is to subtract the correlation values from 1, then the values should be in the right form. The diagonal should then have only 0s. As Nathaniel mentioned, in the input file the diagonal should not be included.

**Comment by akatav** [comment]
@sauln i tried on the web with the live demo. 
my matrix written to the file is like this - the first row has 264 columns and the second row 263 columns and so on.. i asked the question above as this resembles a lower triangular matrix but it's actually an upper triangular one. is this ok? 
also, the file that is uploaded via the web should have extension '.distance_matrix' ? i am uploading a text file. hope this is ok.

@ubauer thanks! i actually tried that just now. as mentioned, i am using the web version. i do not see any output. i mention barcode dimensions as 1-4 to begin with. i attached snapshots of the matrix if that's ok merely for purposes of illustration. 

![ripserweb](https://user-images.githubusercontent.com/721570/34252768-497e4cc0-e688-11e7-85d1-9b4b0da16ba5.png)
![matrix](https://user-images.githubusercontent.com/721570/34252769-49ab9ad6-e688-11e7-8832-58bf63049b41.png)

**Comment by saona-raimundo** [comment]
I agree that it would be useful to have an explanation and example for each type of input, together with the expected result that one should obtain in the online version. For example:

# Distance matrix
- What is its definition?
- Is there an example?
- In that example, what would be computed? 

Thank you beforehand!!

**Comment by jolo2486** [comment]
Just a comment/suggestion (not really an issue) on the topic of the input format here:

Perhaps make explicitly clear in the documentation (I may have missed it though) that the input matrix should be hollow (which is implicit since it's defined as a distance matrix), OR have Ripser completely ignore the diagonal.

I was getting faulty output for H0 when using distance matrices formed through different forms of symmetrization (ending up symmetric but with nonzero diagonal), until I just filled the diagonal with 0:s, then it worked as expected; output for H1 was still the same though.

**Comment by ubauer** [comment]
Do you have an example of a file producing faulty output for H0? I am not sure what is going wrong. Currently Rips should ignore the diagonal of an input distance matrix.

> Just a comment/suggestion (not really an issue) on the topic of the input format here:
> 
> Perhaps make explicitly clear in the documentation (I may have missed it though) that the input matrix should be hollow (which is implicit since it's defined as a distance matrix), OR have Ripser completely ignore the diagonal.
> 
> I was getting faulty output for H0 when using distance matrices formed through different forms of symmetrization (ending up symmetric but with nonzero diagonal), until I just filled the diagonal with 0:s, then it worked as expected; output for H1 was still the same though.
