### ISSUE TITLE
Ripser is not endian-safe (merge request with proposed fix)

### ISSUE THREAD

**Issue by gspr** [Ripser/ripser#21]
Ripser is currently not reading binary formats correctly on big endian architectures.

The branch `gspr/endian-safety` on https://git.nonempty.org/ripser has a proposed solution that doesn't require Boost (as a source code comment in `read` is currently hinting at), and does not change anything for the user unless they explicitly set the `BIGENDIAN` preprocessor definition.

**Comment by mr-gomez** [comment]
Actually, I tried saving a lower distance matrix from MATLAB using fwrite ([manual page](https://www.mathworks.com/help/matlab/ref/fwrite.html)). I explicitely stated in the call to fwrite to use little endian ordering, but it didn't work either.

Example:
```
% Distance matrix of a square
D = [0,1,2,1;
    1,0,1,2;
    2,1,0,1;
    1,2,1,0];
% Get lower triangular matrix
DLT = D(tril(~~D));

% Write to a binary file using little endian.
file_name = 'DLower.bin';
fileID = fopen(file_name,'w');
fwrite(fileID, DLT, 'double', 'l');
fclose(fileID);
```
Ripser output.
```
[user@machine ~]$ ripser/ripser-coeff --dim 2 --threshold 3 --modulus 2 --format binary DLower.bin
value range: [0,2]
distance matrix with 5 points
persistence intervals in dim 0:
 [0, )
persistence intervals in dim 1:
 [0,1.875)
persistence intervals in dim 2:

```
Expected output, using a .txt instead
```
[user@machine ~]$ ripser/ripser-coeff --dim 2 --threshold 3 --modulus 2 --format lower-distance DLower.txt
value range: [1,2]
distance matrix with 4 points
persistence intervals in dim 0:
 [0,1)
 [0,1)
 [0,1)
 [0, )
persistence intervals in dim 1:
 [1,2)
persistence intervals in dim 2:

```

According to [this](https://www.mathworks.com/help/matlab/ref/computer.html) MATLAB page, my computer uses little endian.

```
>> [str, maxsize, endian] = computer

str =

    'GLNXA64'


maxsize =

   2.8147e+14


endian =

    'L'
```

**Comment by ubauer** [comment]
Can you check the file size? It looks like the number of points is wrong, which indicates that the file size might be different from what it should be. Can you send a hex dump of the binary file?

**Comment by mr-gomez** [comment]
Yes, here it is. Also, my computer says the file is 48 bytes.
0000000 0000 0000 0000 3ff0 0000 0000 0000 4000
0000010 0000 0000 0000 3ff0 0000 0000 0000 3ff0
0000020 0000 0000 0000 4000 0000 0000 0000 3ff0
0000030

**Comment by gspr** [comment]
Mario Gómez <notifications@github.com> writes:

> Yes, here it is. Also, my computer says the file is 48 bytes.
> `0000000 0000 0000 0000 3ff0 0000 0000 0000 4000
> 0000010 0000 0000 0000 3ff0 0000 0000 0000 3ff0
> 0000020 0000 0000 0000 4000 0000 0000 0000 3ff0
> 0000030`

The first entry (i.e. a double 1) looks backwards to me. Shouldn't the
exponent and its immediate surroundings become `f03f` rather than `3ff0`
as above?

**Comment by gspr** [comment]
gspr <notifications@github.com> writes:

> Mario Gómez <notifications@github.com> writes:
>
>> Yes, here it is. Also, my computer says the file is 48 bytes.
>> `0000000 0000 0000 0000 3ff0 0000 0000 0000 4000
>> 0000010 0000 0000 0000 3ff0 0000 0000 0000 3ff0
>> 0000020 0000 0000 0000 4000 0000 0000 0000 3ff0
>> 0000030`
>
> The first entry (i.e. a double 1) looks backwards to me. Shouldn't the
> exponent and its immediate surroundings become `f03f` rather than `3ff0`
> as above?

Indeed:

```
X = np.array([[0,1,2,1],
[1,0,1,2],
[2,1,0,1],
[1,2,1,0]], dtype=np.double)

y = X[np.tril_indices(X.shape[0], k=-1)]

with open("test.bin", "wb") as f:
     f.write(struct.pack("<%dd" %(len(y)), *y))
```
```
$ xxd test.bin
00000000: 0000 0000 0000 f03f 0000 0000 0000 0040 
00000010: 0000 0000 0000 f03f 0000 0000 0000 f03f 
00000020: 0000 0000 0000 0040 0000 0000 0000 f03f 

```

Maybe there's some caveats with how Matlab writes binary files? I have
no clue.

**Comment by ubauer** [comment]
Thanks! There is another issue: the binary format should actually use 32 bit floats, not 64 bit doubles. This has been misstated in the readme, it is fixed now.

**Comment by mr-gomez** [comment]
It's working now, thank you!
```
% Write to a binary file using little endian.
file_name = 'DLower.bin';
fileID = fopen(file_name,'w');
fwrite(fileID, DLT, 'float', 'l');
fclose(fileID);
```

Output:
```
[user@machine ~]$ ripser/ripser-coeff --dim 2 --threshold 3 --modulus 2 --format binary DLower.bin
value range: [0,2]
distance matrix with 4 points
persistence intervals in dim 0:
 [0,1)
 [0,1)
 [0,1)
 [0, )
persistence intervals in dim 1:
 [1,2)
persistence intervals in dim 2:
```

> $ xxd test.bin
> 00000000: 0000 0000 0000 f03f 0000 0000 0000 0040
> 00000010: 0000 0000 0000 f03f 0000 0000 0000 f03f
> 00000020: 0000 0000 0000 0040 0000 0000 0000 f03f
> 
> ```
> 
> Maybe there's some caveats with how Matlab writes binary files? I have
> no clue.
> 
For future reference, I used xxd on my file and got the same output as you. I did `hexdump DLower.bin` the first time.
