### ISSUE TITLE
Haskell wrapper

### ISSUE THREAD

**Issue by adamConnerSax** [Ripser/ripser#23]
Not an issue, per se, but just so you know it exists.  I made a Haskell wrapper for ripser.  

It takes a container of items and a distance function, produces a lower-distance-matrix, opens a ripser process, sends the LDM on stdin and then parses the result into a list of Barcodes (using a data structure from  https://hackage.haskell.org/package/Persistence-2.0.3/docs/Persistence-Filtration.html).

The wrapper can be found on github here: https://github.com/adamConnerSax/ripser-haskell.

**Comment by ubauer** [comment]
Thank you!
