### ISSUE TITLE
Typo on line 1125

### ISSUE THREAD

**Issue by tmelorc** [Ripser/ripser#24]
I think it is missing a pair of `()` in line 1125 to right compute the number of elements above the diagonal of the matrix. 

I should be

`(dist.size() * (dist.size() - 1)) / 2 `

**Comment by MassEast** [comment]
Still wrong [here](https://github.com/Ripser/ripser/blob/9c6d3a5d867376cd041e055cf682135c1c3d7502/ripser.cpp#L1287).

**Comment by ubauer** [comment]
Thank you! It is fixed now.
