### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by peter308** [Ripser/ripser#27]
Dear 

When I am using Ripser to do calculations  on distance matrices, I encountered the error message
"MemoryError: std::bad_alloc"

Could you help by providing any solutions, e.g. adding more memory or changing the source codes?

Thank!

Peter

**Comment by ubauer** [comment]
(Duplicate of #28)

Dear Peter,

the exception "std::bad_alloc" means that your computer runs out of memory. See also #28 for a few more details and suggestions.

Best, Uli
