### ISSUE TITLE
How to output the components of certain homology group? 

### ISSUE THREAD

**Issue by peter308** [Ripser/ripser#29]
Dear Dr. Bauer

I have calculated barcodes, and I found a particular persistent homology in the 2-dim, which is more persistent than all other 2-dim homology groups found in the same calculation, How to output the components in that special 2-dim homology group? Are there any options I can use while running Ripser, or do you suggest any example codes on doing this?
 
Thanks!

Best Regards,
Peter

**Comment by ubauer** [comment]
You may take a look at the branch "representative-cocycles" or "representative-cycles" to obtain generators for the corresponding classes in cohomology or homology.
