### ISSUE TITLE
default format of input files

### ISSUE THREAD

**Issue by MonkeyBreaker** [Ripser/ripser#30]
Hi !

First, thank you for the great library.

I was testing `ripser` and looking into the help, it says that the default format used is `lower-distance`.
But, looking into the code, it seems that the default format is [`DISTANCE_MATRIX` ](https://github.com/Ripser/ripser/blob/286d3696796a707eecd0f71e6377880f60c936da/ripser.cpp#L1019).

Am I misunderstanding something ?

PS: The help documentation:

```bash
--format         use the specified file format for the input. Options are:
                     lower-distance (lower triangular distance matrix; default)
                     upper-distance (upper triangular distance matrix)
                     distance       (full distance matrix)
                     point-cloud    (point cloud in Euclidean space)
                     dipha          (distance matrix in DIPHA file format)
                     sparse         (sparse distance matrix in sparse triplet format)
                     binary         (lower triangular distance matrix in binary format)
```

**Comment by ubauer** [comment]
Thanks! I added a clarification of the default input. It is DISTANCE_MATRIX, but only the lower triangular part is read. So you can also input a CSV file with the other entries missing, as long as there is a line in the file per row of the matrix. For the lower-distance option, the input can also be just a single line with all the entries.
