### ISSUE TITLE
Rips not working when I change maxdim

### ISSUE THREAD

**Issue by NewDay1417** [Ripser/ripser#32]
I've been using Rips to make persistence diagrams. It works fine with the default maxdim=1. However, when I change to maxdim=2, I get no output and the stored variables I had disappear. I'm using Spyder to run my code, and all the variables in my variable explorer window disappear when I run maxdim=2. What is happening?

For example, this works fine:
rips=Rips()
dgms_X = rips.fit_transform(data)
plot_diagrams(dgms_X, show=True)

This dies:
rips=Rips(maxdim=2)
dgms_X = rips.fit_transform(data)
plot_diagrams(dgms_X, show=True)

Thank you!!

**Comment by ubauer** [comment]
This seems to be related to the python wrapper ripser.py. I am closing this issue here, as it does not show up in the core C++ code.
