### ISSUE TITLE
Reduced number of 0-dim features

### ISSUE THREAD

**Issue by SPRADA1** [Ripser/ripser#34]
Hi! I am using the package TDAstats with the function calculate_homology that takes ripser functions. I realized that I am always obtaining one feature less in dimension 0 than expected. For example, when I use calculate_homology over a graph with 7 vertices I only obtain 6 features at dimension 0 and that start with a filtration weight 0, why is that? Shouldn't be 7 features? Is it related to the concept of "reduced homology"?
Thanks a lot!

**Comment by ubauer** [comment]
I assume that TDAstats only outputs the non-essential homology. There is always one connected component that remains until the end of the filtration, 

(Closing this issue here as it is unrelated to the core C++ version of Ripser.)
