### ISSUE TITLE
Include ripser as c++ library

### ISSUE THREAD

**Issue by conradhuebler** [Ripser/ripser#39]
Hi. Thanks for the great work.

Is there a chance to include ripser in a c++ project using a header file?

Thanks and cheers
Conrad

**Comment by ubauer** [comment]
Hi,

this is easily possible by removing the main() method from ripser.cpp and turning it into a header file. You can then call ripser.compute_barcodes() like in the main method.

At some point, I might refactor the code to make this possible without editing the files.
