### ISSUE TITLE
ripser-image for different point clouds

### ISSUE THREAD

**Issue by inesgare** [Ripser/ripser#41]
Hi, @ubauer 

First: thank you very much for this incredible package!!

My name is Inés García-Redondo, I’m writing this message with my collaborator @annasongmaths (Anna Song). We’ve been working with your new package ripser-image and we have two questions. Let us assume that we have X and Z rips filtrations coming **from two different point clouds P and P’** respectively, **with the same metric**.

1) Would it be possible to **use ripser-image in this situation**? Currently, we think that the code only admits one single point cloud with two different metrics. We managed a way to do this indirectly: we take P’ as the base point cloud for both filtrations, compute the pairwise distance matrix for Z and then obtain the pairwise distance matrix for X by inflating the distance between any point in P’ \ P (the excluded points) and any point in P’.  This trick prevents edges from forming on excluded points before the full complex has finished growing in the smaller point cloud P.  

2) However this trick is computationally expensive because we are still computing all those steps of the filtration, even though they don’t affect the final result. We tried using **thresholding** to stop the computation before reaching those steps, but we have found that this feature makes some bars disappear, instead of simply truncating the bars as we expected. Is this expectation of ours wrong in the framework of image persistence?

Thanks in advance for your help!

Best,
Inés and Anna

**Comment by inesgare** [comment]
Hi, @ubauer 

As a follow-up to our conversations last week: here is an example of the unexpected behaviour for the thresholding feature. 

We take as our smaller space a circle of radius 1 centred at the origin, sampled with some noise. The bigger space would be the union of that circle and another identical circle centred at 0.5, again sampled with some noise (see picture below)

![example_threshold](https://user-images.githubusercontent.com/92524727/176882618-754a8cd1-054b-4842-afde-7305f0b75c33.png)

To form the corresponding distance matrices: 
- for the bigger space we just compute the pairwise distance 
- for the smaller, we compute the pairwise distance of the points from this space and then set the distance between any other pair of points to maxi = 2 * the maximum pairwise distance of the bigger space.

The matrices obtained are the following:
[X.txt](https://github.com/Ripser/ripser/files/9028427/X.txt)
[Z.txt](https://github.com/Ripser/ripser/files/9028428/Z.txt)

 Without any threshold, using ripser-image with these matrices we obtain the following:
- input: ripser-image --dim 1 --subfiltration X.lower_distance_matrix Z.lower_distance_matrix
- output: 
![without-threshold](https://user-images.githubusercontent.com/92524727/176886284-778d3d51-c666-4da7-90f0-cad9481c7149.png)

Setting as threshold maxi - 1 (which in this case equals 4.153077300038905) we obtain:
- input: ripser-image --dim 1 --threshold 4.153077300038905 --subfiltration X.lower_distance_matrix Z.lower_distance_matrix
- output: 
![with-threshold](https://user-images.githubusercontent.com/92524727/176886711-d747e1a7-9b0e-4a8f-8b6e-bd360f69b0ed.png)
There are no persistence bars, even though the threshold is way bigger that the death time of the persistence bar that appeared before. 

What are we missing here? Thank you very much in advance for your help.

Best,

Inés and Anna

**Comment by ubauer** [comment]
Hi,

the problem should be fixed now (before, the threshold was applied to the wrong filtration, causing some simplices to be cut off).

Best, Uli
