### ISSUE TITLE
Question about apparent pairs 

### ISSUE THREAD

**Issue by peekxc** [Ripser/ripser#48]
This may be a simple question, but how does ripser manage to find all H1 pairs without enumerating all 2-simplices (< threshold)?

In the code, it appears Ripser first finds [positive edges lacking apparent zero cofacets](https://github.com/Ripser/ripser/blob/01add51ff64aaf40889483260cc5c3b7d0f2a1e7/ripser.cpp#L626-L628), and then [enumerates each edge's cofacets](https://github.com/Ripser/ripser/blob/01add51ff64aaf40889483260cc5c3b7d0f2a1e7/ripser.cpp#L675-L688), reducing as it goes along. 

I may be missing something obvious, but how does this compute all H1 pairs? While it is clear that a negative 2-simplex of an apparent H1 pair must indeed be a cofacet of its positive counterpart (by definition of an AP), this isn't true in general.

**Comment by ubauer** [comment]
Thanks for your message. I think that the confusion here mostly stems from your assumption that Ripser obtains all H1 pairs through cofacet enumeration without reduction, which is not the case. In fact, reduction does happen in Ripser when computing H1 as you mentioned, and this is crucial to obtain the complete pairing between birth edges E+ and death triangles T–. The identification of apparent pairs merely provides a shortcut that helps improving the memory usage, and as a consequence also the running time, as memory access is slow compared to arithmetic, but it actually doesn’t affect the running time of the algorithm in terms of column operations. For many geometric data sets, the vast majority of simplices occur in apparent pairs, and so the reduction becomes very fast, but for random Erdős–Renyí fitrations, the expected number of apparent pairs seems to be smaller than for geometric data.

This should not be confused with the statement that Ripser obtains all H1 pairs without necessarily enumerating all triangles. The observation here is that the identification of a zero apparent cofacet does not require the enumeration of all cofacets; the lexicographically first cofacet with same diameter as the simplex is the only possible candidate for such a cofacet, so the enumeration is terminated after that.

To answer your second question: I don’t think that there is an obvious way to obtain the death triangles T– without any reduction. Your strategy for considering a superset of the death triangles, consisting of all triangles except for zero apparent birth triangles, seems to be the best upper approximation one can obtain without reduction. However, I would say that it is not surprising that this set is a bit too large and computations will still be slow.
